### PR TITLE
chore: Regulate version name and update version

### PR DESCRIPTION
**Pull request by ArchieMeng**
Update repo from 2:22.1.1-1 to 2:22.1.8-1deepin

### CODE REVIEW

**Comment by tsic404** [comment]
https://build.deepin.com/package/show/deepin:CI:deepin-community:xwayland:PR-1/xwayland

patch 有问题

**Comment by tsic404** [comment]
> 

patch 还是有问题 :cry:

**Comment by Zeno-sole** [comment]
/+1

**Pull request merged**
